### PR TITLE
Prod1

### PR DESCRIPTION
**Pull request by cjephuneh**
new ui

### CODE REVIEW

**Comment by cjephuneh** [comment]
msifunge hii pr kwanza mreview tuu

**Comment by kechykechy** [comment]
Noted

kechy

**Review by cjephuneh — COMMENTED** [review]
updates

**Review by Cat-Vader — COMMENTED** [review]
There are still a few errors, If you have difficulties in accessing build logs, @kechykechy I think can provide clarity

**Review by Cat-Vader — COMMENTED** [review]
Seen, have you pushed these changes tothe main branch

**Pull request closed without merging**
